name: Vercel Deploy
on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.vscode/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      storybook_status: ${{ steps.build_storybook.outcome }}
      keycloak_status: ${{ steps.build_keycloak.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "yarn"
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      
      - name: Build Storybook
        id: build_storybook
        run: yarn build-storybook
      
      - name: Build Keycloak theme
        id: build_keycloak
        run: yarn run build-keycloak-theme || true
        continue-on-error: true
        
      # Removed the "Create empty dist_keycloak" step as we now handle this conditionally in the deploy job
        
      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook-static
          path: storybook-static/
          retention-days: 1
          
      - name: Upload Keycloak artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist_keycloak
          path: dist_keycloak/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Storybook artifact
        uses: actions/download-artifact@v3
        with:
          name: storybook-static
          path: storybook-static
          
      - name: Download Keycloak artifact
        uses: actions/download-artifact@v3
        with:
          name: dist_keycloak
          path: dist_keycloak
          
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
      
      - name: Configure Git
        run: |
          git config --global user.name "lcaohoanq"
          git config --global user.email "hoangclw@gmail.com"
      
      - name: Deploy to Production
        run: |
          git clone --depth=1 git@github.com:hoangclw/spkcstb.git production-repo
          
          # Always copy Storybook static files
          rm -rf production-repo/storybook-static
          cp -r storybook-static production-repo/
          
          # Only copy dist_keycloak if it exists and has content
          if [ -d "dist_keycloak" ] && [ "$(ls -A dist_keycloak)" ]; then
            rm -rf production-repo/dist_keycloak
            cp -r dist_keycloak production-repo/
            echo "Keycloak theme copied to production repo"
          else
            echo "Skipping Keycloak theme copy - directory missing or empty"
          fi
          
          cd production-repo
          git add .
          
          # Commit with build status info
          git diff --staged --quiet || git commit -m "Deploy from ${{ github.ref_name }} - ${{ github.sha }} | Storybook: ${{ needs.build.outputs.storybook_status }}, Keycloak: ${{ needs.build.outputs.keycloak_status }}"
          git push origin main
